pipeline {
    agent any
    environment {
        MAVEN_TOOL = 'Maven 3'
        IMAGE_NAME = 'mon-entreprise/mon-app-springboot'
        IMAGE_TAG = "${env.BUILD_ID}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Recuperation du code source depuis Git...'
                checkout scm
            }
        }
        stage('Build & Tests') {
            steps {
                echo 'Compilation du projet avec Maven...'
                sh 'cd devops && ./mvnw clean package -DskipTests=false'
            }
            post {
                always {
                    echo "Tests termines - Rapport ignore temporairement"
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                echo 'Simulation: Lance analyse SonarQube'
            }
        }
        stage('Quality Gate') {
            steps {
                echo 'Simulation: Validation de la qualite du code'
            }
        }
        stage('Docker Build') {
            steps {
                echo "Construction de l image Docker : ${IMAGE_NAME}:${IMAGE_TAG}"
                sh 'cd devops && echo "Simulation docker build"'
            }
        }
        stage('Docker Push') {
            steps {
                echo "Simulation: Push de l image"
            }
        }
        stage('Kubernetes Deploy') {
            steps {
                echo "Simulation: Deploiement K8S"
            }
        }
    }
    post {
        success {
            echo "Pipeline termine avec SUCCES."
        }
        failure {
            echo "Le pipeline a ECHOUE."
        }
    }
}
