pipeline {
    agent any
    environment {
        MAVEN_TOOL = 'Maven 3'
        IMAGE_NAME = 'mon-entreprise/mon-app-springboot'
        IMAGE_TAG = "${env.BUILD_ID}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Récupération du code source depuis Git...'
                checkout scm
            }
        }
        stage('Build & Tests') {
            steps {
                echo 'Compilation du projet avec Maven...'
                sh 'cd devops && ./mvnw clean package -DskipTests=false'
            }
            post {
                always {
                    echo "Tests terminés - Rapport ignoré temporairement"
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                echo 'Simulation: Lance analyse SonarQube (Désactivé car nécessite config Jenkins UI)'
                // sh 'cd devops && ./mvnw sonar:sonar -Dsonar.host.url=http://devops-sonarqube:9000'
            }
        }
        stage('Quality Gate') {
            steps {
                echo 'Simulation: Validation de la qualité du code (Quality Gate)'
            }
        }
        stage('Docker Build') {
            steps {
                echo "Construction de l'image Docker : ${IMAGE_NAME}:${IMAGE_TAG}"
                sh "cd devops && docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }
        stage('Docker Push') {
            steps {
                echo "Simulation: Push de l'image (désactivé car nécessite Registry Hub + Identifiants)"
            }
        }
        stage('Kubernetes Deploy') {
            steps {
                echo "Simulation: Déploiement K8S (désactivé car nécessite cluster Kubernetes local + Identifiants Jenkins)"
            }
        }
    }
    post {
        success {
            echo "✅ Pipeline terminé avec SUCCÈS."
        }
        failure {
            echo "❌ Le pipeline a ÉCHOUÉ."
        }
    }
}
