# Exposition des endpoints utiles pour Kubernetes (Sondes de santé)
management.endpoints.web.exposure.include=health,info

# Active de manière explicite les sondes Liveness et Readiness (nécessaires pour deployment.yaml)
management.endpoint.health.probes.enabled=true
